WIP

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -38,4 +38,4 @@ jobs:
 
     - name: Run app
       run: |
-        if [ -f ./main.py -a ./.cache -a -f ./appSettings.json ]; then python ./main.py -av; else echo "App ended with error code $?"; fi
+        bash if [ -f ./main.py -a ./.cache -a -f ./appSettings.json ]; then python ./main.py -av; else echo "App ended with error code $?"; fi
