WIP

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -39,6 +39,6 @@ jobs:
     - name: Run app
       run: |
         ls -a
-        if [[ -e ./main.py && -e ./.cache && -e ./appSettings.json ]]; then python ./main.py -av; else echo "App ended with error code $?"; fi
+        if [[ -e ./main.py && -a ./.cache && -e ./appSettings.json ]]; then python ./main.py -av; else echo "App ended with error code $?"; fi
 
 
