WIP

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -35,6 +35,6 @@ jobs:
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Run app
       run: |
-        if [ -f ./main.py -a -f ./.cache -a -f ./appSettings.json ]; then python ./main.py -av; else echo "App ended with error code $?"; fi
+        if [[ -f ./main.py && -f ./.cache && -f ./appSettings.json ]]; then python ./main.py -av; else echo "App ended with error code $?"; fi
 
 
