Starting to get tests together

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -5,7 +5,8 @@ name: Python application
 run-name: Basic run test
 
 on:
-  pull_request
+  - pull_request
+  - push
 
 permissions:
   contents: read
@@ -36,7 +37,11 @@ jobs:
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-    - name: Run app
+    # - name: Run app
+    #   run: |
+    #     if [ -f ./main.py -a ./.cache -a -f ./appSettings.json ]; then python ./main.py -aq; 
+    #     else echo "App ended with error code $?"; fi
+
+    - name: Test with pytest
       run: |
-        if [ -f ./main.py -a ./.cache -a -f ./appSettings.json ]; then python ./main.py -aq; 
-        else echo "App ended with error code $?"; fi
+        pytest
